development:
  host: 127.0.0.1
  port: 6379
  password:
  username:

test:
  host: 127.0.0.1
  port: 6379
  password:
  username:

production:
  host: <%= ENV['REDIS_HOST'] %>
  port: <%= ENV['REDIS_PORT'].to_i %>
  password: <%= ENV['REDIS_PASSWORD'] %>
  username: <%= ENV['REDIS_USERNAME'] %>
